# Project: 0526test
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = test.o
LINKOBJ  = test.o
LIBS     = -L"D:/DevCppPortable/DevCppPortable/MinGW64/lib" -L"D:/DevCppPortable/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc "../../../../Program Files (x86)/Dev-Cpp/MinGW64/lib/libbgi.a"
INCS     = -I"D:/DevCppPortable/DevCppPortable/MinGW64/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/DevCppPortable/DevCppPortable/MinGW64/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 0526test.exe
CXXFLAGS = $(CXXINCS) -std=c99 -std=c99
CFLAGS   = $(INCS) -std=c99 -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

test.o: test.cpp
	$(CC) -c test.cpp -o test.o $(CFLAGS)
